# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176760844412800/sqlite-feedstock/recipe, last modified Mon Jan  5 10:21:23 2026
# ------------------------------------------------

package:
  name: sqlite
  version: 3.51.1
source:
  patches: null
  sha256: 4f2445cd70479724d32ad015ec7fd37fbb6f6130013bd4bfbc80c32beb42b7e0
  url: https://www.sqlite.org/2025/sqlite-autoconf-3510100.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.51.1,<4.0a0
  string: he0a8d7e_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.44 h4b9a079_2
    - binutils_linux-64 2.44 hc03a8fd_2
    - gcc_impl_linux-64 14.3.0 h4943218_4
    - gcc_linux-64 14.3.0 hda73cce_12
    - kernel-headers_linux-64 4.18.0 h3108a97_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libgcc 15.2.0 h69a1729_7
    - libgcc-devel_linux-64 14.3.0 he7458c1_104
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libsanitizer 14.3.0 hd4faa28_4
    - libstdcxx 15.2.0 h39759b7_7
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.28 h3108a97_1
    - tzdata 2025b h04d1e81_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - ncurses 6.5 h7934f7d_0
    - readline 8.3 hc2a1206_0
    - zlib 1.2.13 hd233ad5_2
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc >=14
    - ncurses >=6.5,<7.0a0
    - readline >=8.3,<9.0a0
    - zlib >=1.2.13,<2.0a0
test:
  commands:
    - sqlite3 --version
    - python -c "import sqlite3; print(sqlite3.sqlite_version)"
    - test -f $PREFIX/bin/sqlite3
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
    - readelf -d $PREFIX/lib/libsqlite3${SHLIB_EXT} | grep SONAME
  requires:
    - binutils
    - python
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine. It is the most used database engine

    in the world.

    '
  dev_url: https://sqlite.org/src/dir?ci=trunk
  doc_url: https://www.sqlite.org/docs.html
  home: https://www.sqlite.org
  license: blessing
  license_family: Other
  license_file: LICENSE.md
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - xylar
