# This file created by conda-build 25.11.1
# meta.yaml template originally from:
# /home/task_177071101768311/pip-feedstock/recipe, last modified Tue Feb 10 08:10:35 2026
# ------------------------------------------------

package:
  name: pip
  version: 26.0.1
source:
  url: https://pypi.org/packages/source/p/pip/pip-26.0.1.tar.gz
  sha256: c4037d8a277c89b320abe636d59f91e6d0922d08a05b60e85e53b296613346d8
build:
  noarch: python
  number: '0'
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  string: pyhc872135_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - flit-core 3.12.0 py314hee27c6d_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.4 h7354ed3_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - lz4-c 1.9.4 h6a678d5_1
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.19 h1b28b03_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.14.2 h90eec9f_101_cp314
    - python_abi 3.14 2_cp314
    - readline 8.3 hc2a1206_0
    - sqlite 3.51.1 he0a8d7e_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025c he532380_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
    - zstd 1.5.7 h11fc155_0
  run:
    - python >=3.9,<3.15.0a0
    - setuptools
    - wheel
test:
  requires:
    - python 3.10.*
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  home: https://pip.pypa.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  description: 'pip is the package installer for Python.

    You can use pip to install packages from the Python Package

    Index and other indexes.

    '
  doc_url: https://pip.pypa.io
  dev_url: https://github.com/pypa/pip
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
    - python_build_tools_in_host
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/pip-feedstock
  sha: 4fbd7267ccbab659777f7e30b163741d601e98dc
  task_id: M2-NMxzlRX-E-L48gIjmeg
  task_run_id: '0'
  pbp_graph_uuid: 400f033e-f2c6-4f6e-9884-cb0aee011edb
