# This file created by conda-build 25.11.1
# meta.yaml template originally from:
# /home/task_176944960760202/wheel-feedstock/recipe, last modified Mon Jan 26 17:57:04 2026
# ------------------------------------------------

package:
  name: wheel
  version: 0.46.3
source:
  url: https://pypi.io/packages/source/w/wheel/wheel-0.46.3.tar.gz
  sha256: e3e79874b07d776c40bd6033f8ddf76a7dad46a7b8aa1b2787a83083519a1803
build:
  number: '0'
  entry_points:
    - wheel = wheel._commands:main
  string: py312h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - expat 2.7.3 h7354ed3_4
    - flit-core 3.12.0 py312hee27c6d_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.3 h7354ed3_4
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libnsl 2.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.12.12 hd17a9e1_1
    - python-installer 0.7.0 pyhd3eb1b0_1
    - readline 8.3 hc2a1206_0
    - sqlite 3.51.1 he0a8d7e_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025c he532380_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - packaging >=24.0
    - python >=3.12,<3.13.0a0
test:
  imports:
    - wheel
    - wheel._commands
  requires:
    - pip
  commands:
    - pip check
    - wheel --help
    - wheel version
about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  final: true
  copy_test_source_files: true
